In [3]:
import numpy as np
list_m = [[1,2,3], [4,5,6], [6,7,8]]
arr_m =np.array(list_m,dtype=np.int16)
print(arr_m)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
import numpy as np
arr_zero = np.zeros((2, 2), dtype=np.int16)
print(arr_zero)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
arr_1= np.ones((1, 2))
print(arr_1)

[[1. 1.]]


In [7]:
import numpy as np
arr_c= np.full((2, 2), 7)
print(arr_c)

[[7 7]
 [7 7]]


In [11]:
import numpy as np
arr_a=np.arange(1,2,3)
print(arr_a)

[1]


In [ ]:
import numpy as np
arr_r=np.random.random((2,2))
print(arr_r*10)

[[4.05694169 8.72376968]
 [8.26903694 7.297065  ]]


In [17]:
import numpy as np
arr_ri=np.random.randint(10,100,7)
print(arr_ri)

[84 53 90 84 88 10 67]


In [4]:
import numpy as np
arr_I =np.eye(2)
print(arr_I)

[[1. 0.]
 [0. 1.]]


In [3]:
import numpy as np
x_1 = (1, 2, 3)
a_1 = np.asarray(x_1)
print(a_1)

import numpy as np
x_2 = [(1, 2, 3), (4,5)]
a_2 = np.asarray(x_2)
print(a_2)

[1 2 3]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.